#
# This Dockerfile build a small docker image packaging a minimal wine setup
# that allows running the Trimble "convertToRinex" utility in command line
# mode on an x86 Linux based system
#
# Official Trimble tool page : https://geospatial.trimble.com/trimble-rinex-converter
#
# Tested with the following versions of trimble required binaries :
# https://dl.trimble.com/osg/survey/gpsconfigfiles/21.9.27/trimblecfgupdate.exe
# https://trl.trimble.com/dscgi/ds.py/Get/File-869391/convertToRinex314.msi
#
# if still available at time when you'll build the image, the binaries will be
# automatically downloaded. Otherwise you may need to get the manually from
# another source and modify the lines 213 & 214 of this file accordingly
#
# The image build has 3 steps :
#
# - stage 1 : a minimal Wine 6.22 build (from source)
# - stage 2 : download and installation of the Trimble binaries
#           : cleanup of the filesystem to have a light final stage image
# - stage 3 : build the final stage image
#
# Author : mathieu.peyrega@gmail.com
#
# Variables that can be modified to match you needs are at the beginning of dockerfile :
# USER_NAME   : name of the non root user inside the container
# USER_PASSWD : password of that user
# USER_UID    : id of the user inside the container which may be matched to the id of user
#               on docker host in order to remove file access persmission issues
# USER_GID    : same idea as previous with group id
# MAKE_JN     : number of build cores used to compile Wine. Adapt to the computer where
#               you'll build the image
#
# DELAY_BETWEEN_INSTALL : this value in seconds is used to wait between some wine calls at
#                         stage2 whren installing the Windows binaries. I noticed a wait is
#                         needed in order to let wineserver and other wine process terminate
#                         cleanly. You may need to increase this value on slow machines
#
# For intellectual property reasons, unless Trimble provides me with a written authorization
# to do so, I will not provide a pre-build docker image because it would contain the Trimble
# binaries and I'm probably not allowed to do so. Even if no specific licence terms are
# provided at install stage
#

ARG BASE_IMAGE="ubuntu"
ARG TAG="noble"
#ARG TAG="focal"
ARG WINE_INSTALL_PREFIX="/opt/wine"
#wine 8.0 rc5
#ARG WINE_TAG="eb3355bcf801b5484aa1ca968fdb051fe5a94bb5"
#wine 9.12
ARG WINE_TAG="b87f35898d22b90e36970e0b1fce1172ba64eb15"
#wine 9.0 rc5
#ARG WINE_TAG="ff1642f32cfcd2efd8d60be1a8cb432d393587c7"
#wine 6.22
#ARG WINE_TAG="986254d6c17ee1e5fb3aed6effcf2766bf1e787e"
ARG USER_NAME=patrice
ARG USER_PASSWD=patrice
ARG USER_UID=67400
ARG USER_GID=67400
ARG MAKE_JN=24
ARG DELAY_BETWEEN_INSTALL=10

#
# Stage 1 : minimal Wine buid
#         : provided tag is the 6.22 devel-branch release tag
#

FROM ${BASE_IMAGE}:${TAG} AS stage1
SHELL ["/bin/bash", "-c"]
ARG WINE_INSTALL_PREFIX
ARG WINE_TAG
ARG USER_NAME
ARG USER_PASSWD
ARG USER_UID
ARG USER_GID
ARG MAKE_JN

# Install prerequisites
RUN dpkg --add-architecture i386 \
    && apt-get update \
    && DEBIAN_FRONTEND="noninteractive" apt-get full-upgrade -y \
    && DEBIAN_FRONTEND="noninteractive" apt-get install -y --no-install-recommends \    
        apt-transport-https \
        ca-certificates \
        cabextract \
        sudo \
        software-properties-common \
        git \
        gpg-agent \
        tzdata \
        unzip \        
        wget \
        winbind \        
        build-essential flex bison python3 git gcc-multilib g++-multilib \
    && DEBIAN_FRONTEND="noninteractive" apt-get clean -y \        
    && rm -rf /var/lib/apt/lists/* 
  
# Checkout Wine Release 6.22    
RUN git clone https://gitlab.winehq.org/wine/wine.git ~/wine-dirs/wine-source \
    && cd ~/wine-dirs/wine-source \
    && git checkout ${WINE_TAG}

# Install more build prerequisites
RUN dpkg --add-architecture i386 \
    && apt-get update \
    && DEBIAN_FRONTEND="noninteractive" apt-get full-upgrade -y \
    && DEBIAN_FRONTEND="noninteractive" apt-get install -y --no-install-recommends \    
	libpng-dev:i386 libtiff-dev:i386 libunwind-dev:i386 libxml2-dev:i386 \
	libxslt1-dev:i386 libjpeg-turbo8-dev:i386 liblcms2-dev:i386 \
    && DEBIAN_FRONTEND="noninteractive" apt-get clean -y \        
    && rm -rf /var/lib/apt/lists/* 

#
# Configuration step :
# I tried to disable as many options as possible while not preventing convertToRinex.exe to install and run
# in command line mode.
# This is mostly the result of an tedious trial & error iterative process
#

RUN cd ~/wine-dirs/wine-source \
&& ./configure --prefix=${WINE_INSTALL_PREFIX} --disable-tests --without-capi --without-alsa --without-gphoto --without-hal --without-dbus --without-oss --without-quicktime --without-v4l2 --without-mingw --without-gstreamer --without-coreaudio --without-cups --without-sane --without-udev --without-xrandr --without-xinerama --without-pcap --without-krb5 --without-openal --without-opencl --without-opengl --without-pulse --without-vkd3d --without-vulkan --without-gssapi --without-x --without-usb --without-fontconfig --without-freetype --without-osmesa --without-xcomposite --without-xcursor --without-xfixes --without-xxf86vm \
--without-xinput --without-xinput2 --without-xshape --without-xshm 


#
#  Installation & initial cleanup inside stage 1
#

RUN cd ~/wine-dirs/wine-source \
    && make -j${MAKE_JN} \
    && make install

RUN strip -s ${WINE_INSTALL_PREFIX}/lib/wine/i386-windows/* \
    && strip -s ${WINE_INSTALL_PREFIX}/lib/wine/i386-unix/* \
    && strip -s ${WINE_INSTALL_PREFIX}/bin/wine \
                ${WINE_INSTALL_PREFIX}/bin/wineserver \
                ${WINE_INSTALL_PREFIX}/bin/wine-preloader \
    && rm -rf ${WINE_INSTALL_PREFIX}/include \
    && rm -rf ${WINE_INSTALL_PREFIX}/lib/wine/i386-unix/*.a \
    && rm -rf ${WINE_INSTALL_PREFIX}/lib/wine/i386-windows/*.a \
    && rm -rf ${WINE_INSTALL_PREFIX}/share/man

#
# Stage 2 : copy/install wine from stage1
#           download and install the binary package from Trimble website
#           cleanup filesystem as much as possible
#
   
FROM ${BASE_IMAGE}:${TAG} as stage2
ARG WINE_INSTALL_PREFIX
ARG USER_NAME
ARG USER_PASSWD
ARG USER_UID
ARG USER_GID
ARG DELAY_BETWEEN_INSTALL
ENV PATH="${WINE_INSTALL_PREFIX}/bin:${PATH}"
ENV WINEDEBUG=-all,-err
SHELL ["/bin/bash", "-c"]

COPY --from=stage1 ${WINE_INSTALL_PREFIX} ${WINE_INSTALL_PREFIX}

# Install prerequisites
RUN dpkg --add-architecture i386 \
    && apt-get update \
    && DEBIAN_FRONTEND="noninteractive" apt-get full-upgrade -y \
    && DEBIAN_FRONTEND="noninteractive" apt-get install -y --no-install-recommends \
        libc6-x32 libx32gcc-s1 lib32stdc++6 \
        apt-transport-https \
        ca-certificates \
        wget \
        sudo \
        nano \
    && DEBIAN_FRONTEND="noninteractive" apt-get clean -y \        
    && rm -rf /var/lib/apt/lists/* 
       
RUN ldconfig

# Download mono installer
COPY download_mono.sh /tmp/download_mono.sh

#PATRICE
RUN sed -i 's/users:x:100:/users:x:67400:/' /etc/group
RUN sed -i 's/60000/67500/' /etc/login.defs

ADD --chown=${USER_UID}:${USER_GID} https://tbcrelease.blob.core.windows.net/update/config/24.6.16/TrimbleCFGUpdate.exe /tmp
ADD --chown=${USER_UID}:${USER_GID} https://trl.trimble.com/docushare/dsweb/Get/Document-1081326/convertToRinex_4.0.1.9.msi /tmp

RUN chmod 755 /tmp/download_mono.sh \
    && /tmp/download_mono.sh "$([[ "$(${WINE_INSTALL_PREFIX}/bin/wine --version)" =~ .*([0-9]{1}.[0-9]{2}) ]] &&  echo ${BASH_REMATCH[1]})" 
    
RUN useradd --shell /bin/bash --uid "${USER_UID}" --gid "${USER_GID}" --password "$(openssl passwd -1 -salt "$(openssl rand -base64 6)" ${USER_PASSWD})" --create-home --home-dir "/home/${USER_NAME}" "${USER_NAME}" \
    && usermod -aG sudo "${USER_NAME}"
#PATRICE
RUN sed -i 's/users:x:100:/users:x:67400:/' /etc/group
RUN sed -i 's/60000/67500/' /etc/login.defs


USER ${USER_NAME}
RUN wine /tmp/TrimbleCFGUpdate.exe /s /x /b"Z:\\tmp" /v"/qn" 2>/dev/null \
    && sleep ${DELAY_BETWEEN_INSTALL} 
RUN wine cmd /c "msiexec /i Z:\\tmp\\TrimbleCFGUpdate.msi ProductLanguage=\"1033\" /quiet" 2>/dev/null \
    && sleep ${DELAY_BETWEEN_INSTALL}
RUN wine cmd /c "msiexec /i Z:\\tmp\\convertToRinex_4.0.1.9.msi ProductLanguage=\"1033\" /quiet" 2>/dev/null

USER root
COPY clean.sh /home/${USER_NAME}/clean.sh
RUN chmod 755 /home/${USER_NAME}/clean.sh
#RUN rm -rf /home/${USER_NAME}/.wine/drive_c/windows/Installer \
#    && rm -rf /tmp/* \
#    && /home/${USER_NAME}/clean.sh ${USER_NAME} ${WINE_INSTALL_PREFIX}

#
# Stage 3 : Final stage : use the minimal build filesystem in one step to get
#           a small image size
#

FROM ${BASE_IMAGE}:${TAG}
ARG WINE_INSTALL_PREFIX
ARG USER_NAME
ARG USER_PASSWD
ARG USER_UID
ARG USER_GID
ENV PATH="${WINE_INSTALL_PREFIX}/bin:${PATH}"
ENV WINEDEBUG=-all,-err
SHELL ["/bin/bash", "-c"]

COPY --from=stage2 ${WINE_INSTALL_PREFIX} ${WINE_INSTALL_PREFIX}

#PATRICE
RUN sed -i 's/users:x:100:/users:x:67400:/' /etc/group
RUN sed -i 's/60000/67500/' /etc/login.defs



# Install prerequisites
RUN dpkg --add-architecture i386 \
    && apt-get update \
    && DEBIAN_FRONTEND="noninteractive" apt-get full-upgrade -y \
    && DEBIAN_FRONTEND="noninteractive" apt-get install -y  \
        apt-transport-https \
        ca-certificates \    
        libc6-x32  lib32stdc++6 \
        sudo \
        nano \        
    && useradd --shell /bin/bash --uid ${USER_UID} --gid ${USER_GID} --password "$(openssl passwd -1 -salt "$(openssl rand -base64 6)" ${USER_PASSWD})" --create-home --home-dir /home/${USER_NAME} ${USER_NAME} \
    && usermod -aG sudo ${USER_NAME} \
    && DEBIAN_FRONTEND="noninteractive" apt-get clean -y \        
    && rm -rf /var/lib/apt/lists/* 

#PATRICE
RUN sed -i 's/users:x:100:/users:x:67400:/' /etc/group
RUN sed -i 's/60000/67500/' /etc/login.defs


      
COPY entrypoint.sh /usr/bin/entrypoint
RUN chmod 755 /usr/bin/entrypoint
COPY --from=stage2 --chown=${USER_UID}:${USER_GID} /home/${USER_NAME}/.wine /home/${USER_NAME}/.wine

USER ${USER_NAME}
ENTRYPOINT ["/usr/bin/entrypoint"]

